name: TotemUlaskawienia
version: '${project.version}'
main: pl.benio.totemulaskawienia.TotemUlaskawieniaPlugin
api-version: '1.21'
author: Benio
description: Totem, ktory po smierci zachowuje caly ekwipunek gracza i nie pozwala wypasc przedmiotom.

commands:
  totemulaskawienia:
    description: Glowna komenda pluginu Totem Ulaskawienia.
    usage: /totemulaskawienia give [ilosc]
    aliases: [totemu, tu]
    permission: totemulaskawienia.give

permissions:
  totemulaskawienia.give:
    description: Pozwala otrzymac Totem Ulaskawienia komenda /totemulaskawienia give.
    default: op
