name: Cwelostwo
version: 1.0.0
main: pl.example.cwelostwo.Cwelostwo
api-version: "1.20"
author: TwojNick
description: Podpala gracza az do smierci.
commands:
  cwelostwo:
    description: Podpala gracza wpisujacego komende az do smierci.
    usage: /cwelostwo
