name: DragonSword
version: 1.0.0
main: pl.dragonsword.DragonSword
api-version: '1.21'
author: DragonSword
description: Smoczy Miecz - netherytowy miecz teleportujacy gracza Perla Endu.

# Rejestracja komendy
commands:
  smoczymiecz:
    description: Daje graczowi Smoczy Miecz.
    usage: /smoczymiecz
    permission: dragonsword.give
    permission-message: "&cNie masz uprawnien do tej komendy."

# Rejestracja uprawnien
permissions:
  dragonsword.give:
    description: Pozwala otrzymac Smoczy Miecz komenda /smoczymiecz.
    default: op
  dragonsword.use:
    description: Pozwala uzywac umiejetnosci Smoczego Miecza.
    default: true
